### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ragmha** [ragmha/eH-understanding-arrays#1]
- [ ] check concat
- [ ] Difference between splice and splice
- [ ] Other uses of  trim()  besides elimination of whitespace use
- [ ]  Look into reduce
- [ ] what is the disadvantage of using filter too much ?
- [ ] what is the use of Array.prototype.some ?
	- [ ] Quick and dirty query on an array for y/n
	- [ ] Using it for add css class
	- [ ] Also for checking for duplicate entry
	- [ ] Overall used for querying an array
- [ ] what is the use of Array.prototype.every ?
	- [ ] Exits on the first failure
	- [ ]  Returns a Boolean
	- [ ]  if you want the value then use filter
